### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by hyped0001** [Paidly/strapi-plugin-reading-time#6]
Hello I'm receiving this error when running `yarn develop` in my strapi project with the standard configuration provided. Any input?

**Comment by shawncarr** [comment]
What version of Strapi?

Does the field exist that you are trying to reference?

**Comment by hyped0001** [comment]
Thanks for the quick response. I believe it does but I may be referencing it incorrectly please see attached image. I also added `readingTime` (type Text) under Information (not pictured here). Is this the correct config for my setup?

`  
"reading-time": {
    enabled: true,
    config: {
      contentTypes: {
        articles: {
          field: "readingTime",
          references: "information",
        },
      },
    },
  }
`

<img width="1242" alt="Screenshot 2022-12-15 at 4 40 17 PM" src="https://user-images.githubusercontent.com/47896164/207972745-7a80e7c1-e562-4250-946c-3e88c535a139.png">

**Comment by shawncarr** [comment]
In your case `information` is a `component`, not a `field`. For example, if you had an `Article` collection with a `readingTime` field that references a `content` rich text field. On Save, the reading time for the `content` field will be put into the `readingTime` field.

This plug-in does not calculate the reading time for a component as it wouldn't know which field would be valid.

Does that make sense?

**Comment by hyped0001** [comment]
Yes it does; I got it working thanks. Is it possible to use this on fields within a component?

**Comment by shawncarr** [comment]
The reading time plug-in works on the lifecycle of `beforeCreate` and `beforeUpdate` and when those events fire the components have already been created/updated and the `data` for the lifecycle event is just a reference to the record(s) for the components. 

For example, if you have an `SEO` component on an `Article` then when you save the data for the `Article` in the lifecycle event would be something like 

```
{
  ...
  readingTime: "",
  seo: {
    id: 1,
    __pivot: { order: 1, field: 'seo', component_type: 'seo' }
  },
}
```

So while you _can_ do the work and get the required data from the component(s), it is beyond what this plug-in is doing at this time. 

We are always accepting of PRs if you would like this to be implemented.
